from __future__ import annotations

from dataclasses import dataclass

@dataclass(frozen=True)
class FloatPositioningSpec:
    effective_key: str
    source_key: str
    request_attr: str
    request_default: float
    positioning_key: str
    min_value: float | None = None
    max_value: float | None = None
    runtime_key: str | None = None
    runtime_positive_only: bool = False


@dataclass(frozen=True)
class IntPositioningSpec:
    effective_key: str
    source_key: str
    request_attr: str
    request_default: int
    positioning_key: str
    min_value: int | None = None
    max_value: int | None = None
    runtime_key: str | None = None
    runtime_positive_only: bool = False


@dataclass(frozen=True)
class BoolPositioningSpec:
    effective_key: str
    source_key: str
    request_attr: str
    request_default: bool
    positioning_key: str
    runtime_key: str | None = None


@dataclass(frozen=True)
class StringPositioningSpec:
    effective_key: str
    source_key: str
    request_attr: str
    request_default: str
    positioning_key: str
    runtime_key: str | None = None
    strip: bool = True


_FLOAT_POSITIONING_SPECS: tuple[FloatPositioningSpec, ...] = (
    FloatPositioningSpec(
        effective_key="effective_book_pressure_block_z_threshold",
        source_key="book_pressure_block_z_threshold_source",
        request_attr="book_pressure_block_z_threshold",
        request_default=1.65,
        positioning_key="book_pressure_block_z_threshold",
        min_value=-10.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_l2_proof_book_pressure_threshold",
        source_key="break_even_l2_proof_book_pressure_threshold_source",
        request_attr="break_even_l2_proof_book_pressure_threshold",
        request_default=0.06,
        positioning_key="break_even_l2_proof_book_pressure_threshold",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_l2_proof_imbalance_threshold",
        source_key="break_even_l2_proof_imbalance_threshold_source",
        request_attr="break_even_l2_proof_imbalance_threshold",
        request_default=0.1,
        positioning_key="break_even_l2_proof_imbalance_threshold",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_l2_proof_signed_threshold",
        source_key="break_even_l2_proof_signed_threshold_source",
        request_attr="break_even_l2_proof_signed_threshold",
        request_default=0.07,
        positioning_key="break_even_l2_proof_signed_threshold",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_ev_relaxation_factor",
        source_key="ev_relaxation_factor_source",
        request_attr="ev_relaxation_factor",
        request_default=0.5,
        positioning_key="ev_relaxation_factor",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_ev_relaxation_threshold",
        source_key="ev_relaxation_threshold_source",
        request_attr="ev_relaxation_threshold",
        request_default=10.0,
        positioning_key="ev_relaxation_threshold",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_micro_confirmation_volume_delta_min_pct",
        source_key="micro_confirmation_volume_delta_min_pct_source",
        request_attr="micro_confirmation_volume_delta_min_pct",
        request_default=0.6,
        positioning_key="micro_confirmation_volume_delta_min_pct",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_signed_aggression_block_z_threshold",
        source_key="signed_aggression_block_z_threshold_source",
        request_attr="signed_aggression_block_z_threshold",
        request_default=1.65,
        positioning_key="signed_aggression_block_z_threshold",
        min_value=-10.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_weak_l2_aggression_threshold",
        source_key="weak_l2_aggression_threshold_source",
        request_attr="weak_l2_aggression_threshold",
        request_default=0.05,
        positioning_key="weak_l2_aggression_threshold",
        min_value=0.0,
    ),    FloatPositioningSpec(
        effective_key="effective_risk_per_trade_pct",
        source_key="risk_per_trade_source",
        request_attr="risk_per_trade_pct",
        request_default=1.0,
        positioning_key="risk_per_trade_pct",
        min_value=0.1,
    ),
    FloatPositioningSpec(
        effective_key="effective_max_position_notional_pct",
        source_key="max_position_notional_source",
        request_attr="max_position_notional_pct",
        request_default=100.0,
        positioning_key="max_position_notional_pct",
        min_value=1.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_max_fill_participation_rate",
        source_key="max_fill_participation_source",
        request_attr="max_fill_participation_rate",
        request_default=0.20,
        positioning_key="max_fill_participation_rate",
        min_value=0.01,
        max_value=1.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_min_fill_ratio",
        source_key="min_fill_ratio_source",
        request_attr="min_fill_ratio",
        request_default=0.35,
        positioning_key="min_fill_ratio",
        min_value=0.01,
        max_value=1.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_partial_take_profit_rr",
        source_key="partial_take_profit_rr_source",
        request_attr="partial_take_profit_rr",
        request_default=1.0,
        positioning_key="partial_take_profit_rr",
        min_value=0.25,
    ),
    FloatPositioningSpec(
        effective_key="effective_partial_take_profit_fraction",
        source_key="partial_take_profit_fraction_source",
        request_attr="partial_take_profit_fraction",
        request_default=0.5,
        positioning_key="partial_take_profit_fraction",
        min_value=0.05,
        max_value=0.95,
    ),
    FloatPositioningSpec(
        effective_key="effective_partial_flow_deterioration_min_r",
        source_key="partial_flow_deterioration_min_r_source",
        request_attr="partial_flow_deterioration_min_r",
        request_default=0.5,
        positioning_key="partial_flow_deterioration_min_r",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_partial_protect_min_mfe_r",
        source_key="partial_protect_min_mfe_r_source",
        request_attr="partial_protect_min_mfe_r",
        request_default=0.0,
        positioning_key="partial_protect_min_mfe_r",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_trailing_stop_pct",
        source_key="trailing_stop_pct_source",
        request_attr="trailing_stop_pct",
        request_default=0.0,
        positioning_key="trailing_stop_pct",
        min_value=0.0,
        runtime_key="trailing_stop_pct",
        runtime_positive_only=True,
    ),
    FloatPositioningSpec(
        effective_key="effective_global_exit_rr_ratio",
        source_key="global_exit_rr_ratio_source",
        request_attr="global_exit_rr_ratio",
        request_default=0.0,
        positioning_key="global_exit_rr_ratio",
        min_value=0.0,
        runtime_key="global_exit_rr_ratio",
        runtime_positive_only=True,
    ),
    FloatPositioningSpec(
        effective_key="effective_global_risk_atr_stop_multiplier",
        source_key="global_risk_atr_stop_multiplier_source",
        request_attr="global_risk_atr_stop_multiplier",
        request_default=0.0,
        positioning_key="global_risk_atr_stop_multiplier",
        min_value=0.0,
        runtime_key="global_risk_atr_stop_multiplier",
        runtime_positive_only=True,
    ),
    FloatPositioningSpec(
        effective_key="effective_global_risk_volume_stop_pct",
        source_key="global_risk_volume_stop_pct_source",
        request_attr="global_risk_volume_stop_pct",
        request_default=0.0,
        positioning_key="global_risk_volume_stop_pct",
        min_value=0.0,
        runtime_key="global_risk_volume_stop_pct",
        runtime_positive_only=True,
    ),
    FloatPositioningSpec(
        effective_key="effective_global_risk_min_stop_loss_pct",
        source_key="global_risk_min_stop_loss_pct_source",
        request_attr="global_risk_min_stop_loss_pct",
        request_default=0.0,
        positioning_key="global_risk_min_stop_loss_pct",
        min_value=0.0,
        runtime_key="global_risk_min_stop_loss_pct",
        runtime_positive_only=True,
    ),
    FloatPositioningSpec(
        effective_key="effective_trailing_activation_pct",
        source_key="trailing_activation_source",
        request_attr="trailing_activation_pct",
        request_default=0.15,
        positioning_key="trailing_activation_pct",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_buffer_pct",
        source_key="break_even_buffer_source",
        request_attr="break_even_buffer_pct",
        request_default=0.03,
        positioning_key="break_even_buffer_pct",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_activation_min_mfe_pct",
        source_key="break_even_activation_min_mfe_source",
        request_attr="break_even_activation_min_mfe_pct",
        request_default=0.0,
        positioning_key="break_even_activation_min_mfe_pct",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_activation_min_r",
        source_key="break_even_activation_min_r_source",
        request_attr="break_even_activation_min_r",
        request_default=0.0,
        positioning_key="break_even_activation_min_r",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_activation_min_r_trending_5m",
        source_key="break_even_activation_min_r_trending_source",
        request_attr="break_even_activation_min_r_trending_5m",
        request_default=0.0,
        positioning_key="break_even_activation_min_r_trending_5m",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_activation_min_r_choppy_5m",
        source_key="break_even_activation_min_r_choppy_source",
        request_attr="break_even_activation_min_r_choppy_5m",
        request_default=0.0,
        positioning_key="break_even_activation_min_r_choppy_5m",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_level_buffer_pct",
        source_key="break_even_level_buffer_source",
        request_attr="break_even_level_buffer_pct",
        request_default=0.02,
        positioning_key="break_even_level_buffer_pct",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_level_max_distance_pct",
        source_key="break_even_level_max_distance_source",
        request_attr="break_even_level_max_distance_pct",
        request_default=0.60,
        positioning_key="break_even_level_max_distance_pct",
        min_value=0.01,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_l2_signed_aggression_min",
        source_key="break_even_l2_signed_source",
        request_attr="break_even_l2_signed_aggression_min",
        request_default=0.12,
        positioning_key="break_even_l2_signed_aggression_min",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_l2_imbalance_min",
        source_key="break_even_l2_imbalance_source",
        request_attr="break_even_l2_imbalance_min",
        request_default=0.15,
        positioning_key="break_even_l2_imbalance_min",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_l2_book_pressure_min",
        source_key="break_even_l2_book_source",
        request_attr="break_even_l2_book_pressure_min",
        request_default=0.10,
        positioning_key="break_even_l2_book_pressure_min",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_l2_spread_bps_max",
        source_key="break_even_l2_spread_source",
        request_attr="break_even_l2_spread_bps_max",
        request_default=12.0,
        positioning_key="break_even_l2_spread_bps_max",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_costs_pct",
        source_key="break_even_costs_source",
        request_attr="break_even_costs_pct",
        request_default=0.03,
        positioning_key="break_even_costs_pct",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_min_buffer_pct",
        source_key="break_even_min_buffer_source",
        request_attr="break_even_min_buffer_pct",
        request_default=0.05,
        positioning_key="break_even_min_buffer_pct",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_atr_buffer_k",
        source_key="break_even_atr_buffer_source",
        request_attr="break_even_atr_buffer_k",
        request_default=0.10,
        positioning_key="break_even_atr_buffer_k",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_5m_atr_buffer_k",
        source_key="break_even_5m_atr_buffer_source",
        request_attr="break_even_5m_atr_buffer_k",
        request_default=0.10,
        positioning_key="break_even_5m_atr_buffer_k",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_tick_size",
        source_key="break_even_tick_size_source",
        request_attr="break_even_tick_size",
        request_default=0.01,
        positioning_key="break_even_tick_size",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_5m_no_go_proximity_pct",
        source_key="break_even_5m_no_go_source",
        request_attr="break_even_5m_no_go_proximity_pct",
        request_default=0.10,
        positioning_key="break_even_5m_no_go_proximity_pct",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_5m_mfe_atr_factor",
        source_key="break_even_5m_mfe_atr_source",
        request_attr="break_even_5m_mfe_atr_factor",
        request_default=0.15,
        positioning_key="break_even_5m_mfe_atr_factor",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_5m_l2_bias_threshold",
        source_key="break_even_5m_l2_bias_source",
        request_attr="break_even_5m_l2_bias_threshold",
        request_default=0.10,
        positioning_key="break_even_5m_l2_bias_threshold",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_break_even_5m_l2_bias_tighten_factor",
        source_key="break_even_5m_l2_tighten_source",
        request_attr="break_even_5m_l2_bias_tighten_factor",
        request_default=0.85,
        positioning_key="break_even_5m_l2_bias_tighten_factor",
        min_value=0.1,
        max_value=2.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_adverse_flow_threshold",
        source_key="adverse_flow_threshold_source",
        request_attr="adverse_flow_threshold",
        request_default=0.12,
        positioning_key="adverse_flow_threshold",
        min_value=0.02,
    ),
    FloatPositioningSpec(
        effective_key="effective_fixed_stop_loss_pct",
        source_key="fixed_stop_loss_source",
        request_attr="fixed_stop_loss_pct",
        request_default=0.0,
        positioning_key="fixed_stop_loss_pct",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_tcbbo_min_net_premium",
        source_key="tcbbo_min_net_premium_source",
        request_attr="tcbbo_min_net_premium",
        request_default=0.0,
        positioning_key="tcbbo_min_net_premium",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_tcbbo_sweep_boost",
        source_key="tcbbo_sweep_boost_source",
        request_attr="tcbbo_sweep_boost",
        request_default=5.0,
        positioning_key="tcbbo_sweep_boost",
        min_value=0.0,
        max_value=20.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_intraday_levels_micro_confirmation_intrabar_min_move_pct",
        source_key="intraday_levels_micro_confirmation_intrabar_min_move_pct_source",
        request_attr="intraday_levels_micro_confirmation_intrabar_min_move_pct",
        request_default=0.02,
        positioning_key="intraday_levels_micro_confirmation_intrabar_min_move_pct",
        min_value=0.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_intraday_levels_micro_confirmation_intrabar_min_push_ratio",
        source_key="intraday_levels_micro_confirmation_intrabar_min_push_ratio_source",
        request_attr="intraday_levels_micro_confirmation_intrabar_min_push_ratio",
        request_default=0.10,
        positioning_key="intraday_levels_micro_confirmation_intrabar_min_push_ratio",
        min_value=0.0,
        max_value=1.0,
    ),
    FloatPositioningSpec(
        effective_key="effective_intraday_levels_micro_confirmation_intrabar_max_spread_bps",
        source_key="intraday_levels_micro_confirmation_intrabar_max_spread_bps_source",
        request_attr="intraday_levels_micro_confirmation_intrabar_max_spread_bps",
        request_default=12.0,
        positioning_key="intraday_levels_micro_confirmation_intrabar_max_spread_bps",
        min_value=0.0,
    ),
)


_INT_POSITIONING_SPECS: tuple[IntPositioningSpec, ...] = (
    IntPositioningSpec(
        effective_key="effective_intraday_levels_bounce_conflict_buffer_bars",
        source_key="intraday_levels_bounce_conflict_buffer_bars_source",
        request_attr="intraday_levels_bounce_conflict_buffer_bars",
        request_default=2,
        positioning_key="intraday_levels_bounce_conflict_buffer_bars",
        min_value=0,
    ),
    IntPositioningSpec(
        effective_key="effective_weak_l2_break_even_min_hold_bars",
        source_key="weak_l2_break_even_min_hold_bars_source",
        request_attr="weak_l2_break_even_min_hold_bars",
        request_default=1,
        positioning_key="weak_l2_break_even_min_hold_bars",
        min_value=0,
    ),    IntPositioningSpec(
        effective_key="effective_break_even_min_hold_bars",
        source_key="break_even_min_hold_source",
        request_attr="break_even_min_hold_bars",
        request_default=5,
        positioning_key="break_even_min_hold_bars",
        min_value=1,
    ),
    IntPositioningSpec(
        effective_key="effective_break_even_level_min_confluence",
        source_key="break_even_level_min_confluence_source",
        request_attr="break_even_level_min_confluence",
        request_default=2,
        positioning_key="break_even_level_min_confluence",
        min_value=0,
    ),
    IntPositioningSpec(
        effective_key="effective_break_even_level_min_tests",
        source_key="break_even_level_min_tests_source",
        request_attr="break_even_level_min_tests",
        request_default=1,
        positioning_key="break_even_level_min_tests",
        min_value=0,
    ),
    IntPositioningSpec(
        effective_key="effective_break_even_min_tick_buffer",
        source_key="break_even_min_tick_buffer_source",
        request_attr="break_even_min_tick_buffer",
        request_default=1,
        positioning_key="break_even_min_tick_buffer",
        min_value=0,
    ),
    IntPositioningSpec(
        effective_key="effective_break_even_anti_spike_bars",
        source_key="break_even_anti_spike_bars_source",
        request_attr="break_even_anti_spike_bars",
        request_default=1,
        positioning_key="break_even_anti_spike_bars",
        min_value=0,
    ),
    IntPositioningSpec(
        effective_key="effective_break_even_anti_spike_hits_required",
        source_key="break_even_anti_spike_hits_source",
        request_attr="break_even_anti_spike_hits_required",
        request_default=2,
        positioning_key="break_even_anti_spike_hits_required",
        min_value=1,
    ),
    IntPositioningSpec(
        effective_key="effective_time_exit_bars",
        source_key="time_exit_source",
        request_attr="time_exit_bars",
        request_default=40,
        positioning_key="time_exit_bars",
        min_value=1,
        runtime_key="time_exit_bars",
        runtime_positive_only=True,
    ),
    IntPositioningSpec(
        effective_key="effective_adverse_flow_min_hold_bars",
        source_key="adverse_flow_min_hold_source",
        request_attr="adverse_flow_min_hold_bars",
        request_default=3,
        positioning_key="adverse_flow_min_hold_bars",
        min_value=1,
    ),
    IntPositioningSpec(
        effective_key="effective_tcbbo_lookback_bars",
        source_key="tcbbo_lookback_bars_source",
        request_attr="tcbbo_lookback_bars",
        request_default=5,
        positioning_key="tcbbo_lookback_bars",
        min_value=1,
    ),
    IntPositioningSpec(
        effective_key="effective_intraday_levels_micro_confirmation_bars",
        source_key="intraday_levels_micro_confirmation_bars_source",
        request_attr="intraday_levels_micro_confirmation_bars",
        request_default=2,
        positioning_key="intraday_levels_micro_confirmation_bars",
        min_value=1,
    ),
    IntPositioningSpec(
        effective_key="effective_intraday_levels_micro_confirmation_sweep_bars",
        source_key="intraday_levels_micro_confirmation_sweep_bars_source",
        request_attr="intraday_levels_micro_confirmation_sweep_bars",
        request_default=0,
        positioning_key="intraday_levels_micro_confirmation_sweep_bars",
        min_value=0,
    ),
    IntPositioningSpec(
        effective_key="effective_intraday_levels_micro_confirmation_intrabar_window_seconds",
        source_key="intraday_levels_micro_confirmation_intrabar_window_seconds_source",
        request_attr="intraday_levels_micro_confirmation_intrabar_window_seconds",
        request_default=5,
        positioning_key="intraday_levels_micro_confirmation_intrabar_window_seconds",
        min_value=1,
        max_value=60,
    ),
    IntPositioningSpec(
        effective_key="effective_intraday_levels_micro_confirmation_intrabar_min_coverage_points",
        source_key="intraday_levels_micro_confirmation_intrabar_min_coverage_points_source",
        request_attr="intraday_levels_micro_confirmation_intrabar_min_coverage_points",
        request_default=3,
        positioning_key="intraday_levels_micro_confirmation_intrabar_min_coverage_points",
        min_value=0,
    ),
)


_BOOL_POSITIONING_SPECS: tuple[BoolPositioningSpec, ...] = (
    BoolPositioningSpec(
        effective_key="effective_ev_relaxation_enabled",
        source_key="ev_relaxation_enabled_source",
        request_attr="ev_relaxation_enabled",
        request_default=True,
        positioning_key="ev_relaxation_enabled",
    ),
    BoolPositioningSpec(
        effective_key="effective_hard_l2_block_enabled",
        source_key="hard_l2_block_enabled_source",
        request_attr="hard_l2_block_enabled",
        request_default=True,
        positioning_key="hard_l2_block_enabled",
    ),
    BoolPositioningSpec(
        effective_key="effective_time_of_day_filter_enabled",
        source_key="time_of_day_filter_enabled_source",
        request_attr="time_of_day_filter_enabled",
        request_default=True,
        positioning_key="time_of_day_filter_enabled",
    ),
    BoolPositioningSpec(
        effective_key="effective_weak_l2_fast_break_even_enabled",
        source_key="weak_l2_fast_break_even_enabled_source",
        request_attr="weak_l2_fast_break_even_enabled",
        request_default=False,
        positioning_key="weak_l2_fast_break_even_enabled",
    ),    BoolPositioningSpec(
        effective_key="effective_enable_partial_take_profit",
        source_key="partial_take_profit_enabled_source",
        request_attr="enable_partial_take_profit",
        request_default=True,
        positioning_key="enable_partial_take_profit",
    ),
    BoolPositioningSpec(
        effective_key="effective_partial_flow_deterioration_skip_be",
        source_key="partial_flow_deterioration_skip_be_source",
        request_attr="partial_flow_deterioration_skip_be",
        request_default=True,
        positioning_key="partial_flow_deterioration_skip_be",
    ),
    BoolPositioningSpec(
        effective_key="effective_break_even_activation_use_levels",
        source_key="break_even_activation_use_levels_source",
        request_attr="break_even_activation_use_levels",
        request_default=True,
        positioning_key="break_even_activation_use_levels",
    ),
    BoolPositioningSpec(
        effective_key="effective_break_even_activation_use_l2",
        source_key="break_even_activation_use_l2_source",
        request_attr="break_even_activation_use_l2",
        request_default=True,
        positioning_key="break_even_activation_use_l2",
    ),
    BoolPositioningSpec(
        effective_key="effective_break_even_movement_formula_enabled",
        source_key="break_even_movement_formula_enabled_source",
        request_attr="break_even_movement_formula_enabled",
        request_default=False,
        positioning_key="break_even_movement_formula_enabled",
    ),
    BoolPositioningSpec(
        effective_key="effective_break_even_proof_formula_enabled",
        source_key="break_even_proof_formula_enabled_source",
        request_attr="break_even_proof_formula_enabled",
        request_default=False,
        positioning_key="break_even_proof_formula_enabled",
    ),
    BoolPositioningSpec(
        effective_key="effective_break_even_activation_formula_enabled",
        source_key="break_even_activation_formula_enabled_source",
        request_attr="break_even_activation_formula_enabled",
        request_default=False,
        positioning_key="break_even_activation_formula_enabled",
    ),
    BoolPositioningSpec(
        effective_key="effective_break_even_trailing_handoff_formula_enabled",
        source_key="break_even_trailing_handoff_formula_enabled_source",
        request_attr="break_even_trailing_handoff_formula_enabled",
        request_default=False,
        positioning_key="break_even_trailing_handoff_formula_enabled",
    ),
    BoolPositioningSpec(
        effective_key="effective_break_even_anti_spike_require_close_beyond",
        source_key="break_even_anti_spike_close_source",
        request_attr="break_even_anti_spike_require_close_beyond",
        request_default=True,
        positioning_key="break_even_anti_spike_require_close_beyond",
    ),
    BoolPositioningSpec(
        effective_key="effective_trailing_enabled_in_choppy",
        source_key="trailing_enabled_in_choppy_source",
        request_attr="trailing_enabled_in_choppy",
        request_default=False,
        positioning_key="trailing_enabled_in_choppy",
    ),
    BoolPositioningSpec(
        effective_key="effective_adverse_flow_exit_enabled",
        source_key="adverse_flow_exit_enabled_source",
        request_attr="adverse_flow_exit_enabled",
        request_default=True,
        positioning_key="adverse_flow_exit_enabled",
    ),
    BoolPositioningSpec(
        effective_key="effective_time_exit_formula_enabled",
        source_key="time_exit_formula_enabled_source",
        request_attr="time_exit_formula_enabled",
        request_default=False,
        positioning_key="time_exit_formula_enabled",
    ),
    BoolPositioningSpec(
        effective_key="effective_adverse_flow_exit_formula_enabled",
        source_key="adverse_flow_exit_formula_enabled_source",
        request_attr="adverse_flow_exit_formula_enabled",
        request_default=False,
        positioning_key="adverse_flow_exit_formula_enabled",
    ),
    BoolPositioningSpec(
        effective_key="effective_tcbbo_gate_enabled",
        source_key="tcbbo_gate_enabled_source",
        request_attr="tcbbo_gate_enabled",
        request_default=False,
        positioning_key="tcbbo_gate_enabled",
    ),
    BoolPositioningSpec(
        effective_key="effective_intraday_levels_micro_confirmation_enabled",
        source_key="intraday_levels_micro_confirmation_enabled_source",
        request_attr="intraday_levels_micro_confirmation_enabled",
        request_default=False,
        positioning_key="intraday_levels_micro_confirmation_enabled",
    ),
    BoolPositioningSpec(
        effective_key="effective_intraday_levels_micro_confirmation_disable_for_sweep",
        source_key="intraday_levels_micro_confirmation_disable_for_sweep_source",
        request_attr="intraday_levels_micro_confirmation_disable_for_sweep",
        request_default=False,
        positioning_key="intraday_levels_micro_confirmation_disable_for_sweep",
    ),
    BoolPositioningSpec(
        effective_key="effective_intraday_levels_micro_confirmation_require_intrabar",
        source_key="intraday_levels_micro_confirmation_require_intrabar_source",
        request_attr="intraday_levels_micro_confirmation_require_intrabar",
        request_default=False,
        positioning_key="intraday_levels_micro_confirmation_require_intrabar",
    ),
)


_STRING_POSITIONING_SPECS: tuple[StringPositioningSpec, ...] = (
    StringPositioningSpec(
        effective_key="effective_break_even_proof_logic",
        source_key="break_even_proof_logic_source",
        request_attr="break_even_proof_logic",
        request_default="OR",
        positioning_key="break_even_proof_logic",
    ),
    StringPositioningSpec(
        effective_key="effective_micro_confirmation_mode",
        source_key="micro_confirmation_mode_source",
        request_attr="micro_confirmation_mode",
        request_default="volume_delta",
        positioning_key="micro_confirmation_mode",
    ),
    StringPositioningSpec(
        effective_key="effective_volume_profile_poc_mode",
        source_key="volume_profile_poc_mode_source",
        request_attr="volume_profile_poc_mode",
        request_default="favor_bounce_mean_reversion",
        positioning_key="volume_profile_poc_mode",
    ),    StringPositioningSpec(
        effective_key="effective_break_even_movement_formula",
        source_key="break_even_movement_formula_source",
        request_attr="break_even_movement_formula",
        request_default="",
        positioning_key="break_even_movement_formula",
    ),
    StringPositioningSpec(
        effective_key="effective_break_even_proof_formula",
        source_key="break_even_proof_formula_source",
        request_attr="break_even_proof_formula",
        request_default="",
        positioning_key="break_even_proof_formula",
    ),
    StringPositioningSpec(
        effective_key="effective_break_even_activation_formula",
        source_key="break_even_activation_formula_source",
        request_attr="break_even_activation_formula",
        request_default="",
        positioning_key="break_even_activation_formula",
    ),
    StringPositioningSpec(
        effective_key="effective_break_even_trailing_handoff_formula",
        source_key="break_even_trailing_handoff_formula_source",
        request_attr="break_even_trailing_handoff_formula",
        request_default="",
        positioning_key="break_even_trailing_handoff_formula",
    ),
    StringPositioningSpec(
        effective_key="effective_time_exit_formula",
        source_key="time_exit_formula_source",
        request_attr="time_exit_formula",
        request_default="",
        positioning_key="time_exit_formula",
    ),
    StringPositioningSpec(
        effective_key="effective_adverse_flow_exit_formula",
        source_key="adverse_flow_exit_formula_source",
        request_attr="adverse_flow_exit_formula",
        request_default="",
        positioning_key="adverse_flow_exit_formula",
    ),
)


