import type {
  ExecutionModuleDefinition,
  ExecutionModuleField,
} from "../executionModulesTypes";

export const MACRO_REGIMES = ["TRENDING", "CHOPPY", "MIXED"];
export const MICRO_REGIMES = [
  "TRENDING_UP",
  "TRENDING_DOWN",
  "CHOPPY",
  "ABSORPTION",
  "BREAKOUT",
  "MIXED",
];

export const DEFAULT_STRATEGIES = [
  "mean_reversion",
  "momentum",
  "pullback",
  "rotation",
  "vwap_magnet",
  "volume_profile",
  "gap_liquidity",
  "absorption_reversal",
  "momentum_flow",
  "scalp_l2_intrabar",
  "exhaustion_fade",
];

export const DEFAULT_FLOW_BIAS_STRATEGIES = [
  "momentum_flow",
  "absorption_reversal",
  "exhaustion_fade",
  "scalp_l2_intrabar",
];

export const DEFAULT_REGIME_PREFERENCES: Record<string, string[]> = {
  TRENDING: [
    "momentum_flow",
    "momentum",
    "pullback",
    "gap_liquidity",
    "scalp_l2_intrabar",
    "volume_profile",
    "vwap_magnet",
  ],
  CHOPPY: [
    "absorption_reversal",
    "exhaustion_fade",
    "mean_reversion",
    "vwap_magnet",
    "scalp_l2_intrabar",
    "volume_profile",
  ],
  MIXED: [
    "exhaustion_fade",
    "absorption_reversal",
    "volume_profile",
    "gap_liquidity",
    "scalp_l2_intrabar",
    "mean_reversion",
    "vwap_magnet",
    "rotation",
  ],
};

export const DEFAULT_MICRO_PREFERENCES: Record<string, string[]> = {
  TRENDING_UP: ["momentum_flow", "momentum", "pullback", "gap_liquidity", "scalp_l2_intrabar"],
  TRENDING_DOWN: ["momentum_flow", "momentum", "gap_liquidity", "pullback", "scalp_l2_intrabar"],
  CHOPPY: ["absorption_reversal", "exhaustion_fade", "mean_reversion", "vwap_magnet"],
  ABSORPTION: ["absorption_reversal", "exhaustion_fade", "vwap_magnet"],
  BREAKOUT: ["momentum_flow", "momentum", "gap_liquidity", "scalp_l2_intrabar"],
  MIXED: ["exhaustion_fade", "volume_profile", "rotation"],
};

export const STUDIO_PROFILE_LIST_KEY = "adaptive_studio_profiles";
export const STUDIO_PROFILE_ACTIVE_KEY = "active_adaptive_studio_profile_id";
export const STUDIO_PROFILE_MAX_ITEMS = 30;

export const EXECUTION_MODULES: ExecutionModuleDefinition[] = [
  {
    key: "adverse_flow_exit",
    label: "Adverse Flow Exit",
    category: "exit",
    description: "Protective exit when post-entry flow turns against the position.",
    configKey: "adverse_flow_exit_enabled",
  },
  {
    key: "l2_confirmation_gate",
    label: "L2 Confirmation Gate",
    category: "flow",
    description: "Requires L2 microstructure confirmation before entry.",
    configKey: "l2_confirm_enabled",
  },
  {
    key: "trailing_stop",
    label: "Trailing Stop",
    category: "risk",
    description: "Break-even and trailing controls for in-trade risk management.",
    configKey: "trailing_enabled_in_choppy",
  },
  {
    key: "momentum_route",
    label: "Momentum Route",
    category: "flow",
    description: "Flow-based routing constraints for momentum entries.",
    configKey: "momentum_route_enabled",
  },
  {
    key: "momentum_fail_fast",
    label: "Momentum Fail-Fast",
    category: "exit",
    description: "Early-exit guardrails when momentum flow deteriorates.",
    configKey: "momentum_fail_fast_exit_enabled",
  },
  {
    key: "momentum_diversification",
    label: "Momentum Diversification",
    category: "risk",
    description: "Optional run-level override for momentum diversification behavior.",
    configKey: "momentum_diversification_enabled",
  },
  {
    key: "aos_auto_apply",
    label: "AOS Auto-Apply",
    category: "engine",
    description: "Applies active AOS/adaptive optimizations during run start.",
    configKey: "apply_aos_optimizations_on_start",
  },
];

export const EXECUTION_MODULE_CATEGORY_LABELS: Record<string, string> = {
  flow: "Flow",
  exit: "Exit",
  risk: "Risk",
  engine: "Engine",
};

export const EXECUTION_MODULE_PROFILE_KEYS = EXECUTION_MODULES.map((module) => module.configKey);

export const EXECUTION_MODULE_PARAM_FIELDS: ExecutionModuleField[] = [
  {
    moduleKey: "trailing_stop",
    key: "trailing_stop_pct",
    label: "Global Trailing Stop %",
    type: "number",
    min: 0,
    max: 5,
    step: 0.01,
    fallback: 0.8,
    integer: false,
  },
  {
    moduleKey: "trailing_stop",
    key: "global_exit_rr_ratio",
    label: "Global Exit RR Ratio",
    type: "number",
    min: 0,
    max: 10,
    step: 0.05,
    fallback: 2.0,
    integer: false,
  },
  {
    moduleKey: "trailing_stop",
    key: "global_risk_atr_stop_multiplier",
    label: "Global Risk ATR Stop Multiplier",
    type: "number",
    min: 0,
    max: 10,
    step: 0.05,
    fallback: 1.0,
    integer: false,
  },
  {
    moduleKey: "trailing_stop",
    key: "global_risk_volume_stop_pct",
    label: "Global Risk Volume Stop %",
    type: "number",
    min: 0,
    max: 10,
    step: 0.05,
    fallback: 1.0,
    integer: false,
  },
  {
    moduleKey: "trailing_stop",
    key: "global_risk_min_stop_loss_pct",
    label: "Global Risk Min Stop %",
    type: "number",
    min: 0,
    max: 5,
    step: 0.01,
    fallback: 0.05,
    integer: false,
  },
  {
    moduleKey: "trailing_stop",
    key: "trailing_activation_pct",
    label: "Trailing Activation %",
    type: "number",
    min: 0,
    max: 5,
    step: 0.01,
    fallback: 0.45,
    integer: false,
  },
  {
    moduleKey: "trailing_stop",
    key: "break_even_buffer_pct",
    label: "Break-even Buffer %",
    type: "number",
    min: 0,
    max: 2,
    step: 0.01,
    fallback: 0,
    integer: false,
  },
  {
    moduleKey: "trailing_stop",
    key: "break_even_min_hold_bars",
    label: "Break-even Min Hold Bars",
    type: "number",
    min: 1,
    max: 50,
    step: 1,
    fallback: 2,
    integer: true,
  },
  {
    moduleKey: "trailing_stop",
    key: "time_exit_bars",
    label: "Time Exit Bars",
    type: "number",
    min: 1,
    max: 300,
    step: 1,
    fallback: 40,
    integer: true,
  },
  {
    moduleKey: "trailing_stop",
    key: "stop_loss_mode",
    label: "Stop-Loss Mode",
    type: "select",
    options: [
      { value: "strategy", label: "strategy (use strategy stop)" },
      { value: "fixed", label: "fixed (always fixed % stop)" },
      { value: "capped", label: "capped (cap wide strategy stops)" },
    ],
    fallback: "strategy",
  },
  {
    moduleKey: "trailing_stop",
    key: "fixed_stop_loss_pct",
    label: "Fixed Stop-Loss %",
    type: "number",
    min: 0,
    max: 5,
    step: 0.05,
    fallback: 0,
    integer: false,
    disabledWhen: (configSnapshot) =>
      String(configSnapshot?.stop_loss_mode || "strategy").toLowerCase() === "strategy",
  },
  {
    moduleKey: "adverse_flow_exit",
    key: "adverse_flow_threshold",
    label: "Adverse Flow Threshold",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fallback: 0.12,
    integer: false,
  },
  {
    moduleKey: "adverse_flow_exit",
    key: "adverse_flow_min_hold_bars",
    label: "Adverse Flow Min Hold Bars",
    type: "number",
    min: 1,
    max: 50,
    step: 1,
    fallback: 3,
    integer: true,
  },
  {
    moduleKey: "l2_confirmation_gate",
    key: "l2_min_imbalance",
    label: "L2 Min Imbalance",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fallback: 0,
    integer: false,
  },
  {
    moduleKey: "l2_confirmation_gate",
    key: "l2_min_directional_consistency",
    label: "L2 Min Directional Consistency",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fallback: 0,
    integer: false,
  },
  {
    moduleKey: "l2_confirmation_gate",
    key: "l2_min_signed_aggression",
    label: "L2 Min Signed Aggression",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fallback: 0,
    integer: false,
  },
  {
    moduleKey: "l2_confirmation_gate",
    key: "l2_lookback_bars",
    label: "L2 Lookback Bars",
    type: "number",
    min: 1,
    max: 50,
    step: 1,
    fallback: 3,
    integer: true,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_min_flow_score",
    label: "Momentum Min Flow Score",
    type: "number",
    min: 0,
    max: 100,
    step: 0.5,
    fallback: 58,
    integer: false,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_route_flow_score_impulse",
    label: "Momentum Route Flow Impulse",
    type: "number",
    min: 0,
    max: 100,
    step: 0.5,
    fallback: 64,
    integer: false,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_min_directional_consistency",
    label: "Momentum Min Directional Consistency",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fallback: 0.45,
    integer: false,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_min_signed_aggression",
    label: "Momentum Min Signed Aggression",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fallback: 0.04,
    integer: false,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_min_imbalance",
    label: "Momentum Min Imbalance",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fallback: 0.02,
    integer: false,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_min_cvd",
    label: "Momentum Min CVD",
    type: "number",
    min: -1000000000,
    max: 1000000000,
    step: 1,
    fallback: 0,
    integer: false,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_min_directional_price_change_pct",
    label: "Momentum Min Directional Price Change %",
    type: "number",
    min: -100,
    max: 100,
    step: 0.01,
    fallback: 0,
    integer: false,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_min_price_trend_efficiency",
    label: "Momentum Min Price Trend Efficiency",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fallback: 0,
    integer: false,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_min_last_bar_body_ratio",
    label: "Momentum Min Last Bar Body Ratio",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fallback: 0,
    integer: false,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_min_last_bar_close_location",
    label: "Momentum Min Last Bar Close Location",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fallback: 0,
    integer: false,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_min_delta_acceleration",
    label: "Momentum Min Delta Acceleration",
    type: "number",
    min: -1000000000,
    max: 1000000000,
    step: 1,
    fallback: 0,
    integer: false,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_min_delta_price_divergence",
    label: "Momentum Min Delta-Price Divergence",
    type: "number",
    min: -10,
    max: 10,
    step: 0.01,
    fallback: 0,
    integer: false,
  },
  {
    moduleKey: "momentum_route",
    key: "momentum_route_require_l2_coverage",
    label: "Momentum Route Requires L2 Coverage",
    type: "boolean",
    fallback: true,
  },
  {
    moduleKey: "momentum_fail_fast",
    key: "momentum_fail_fast_max_bars",
    label: "Momentum Fail-fast Max Bars",
    type: "number",
    min: 1,
    max: 30,
    step: 1,
    fallback: 3,
    integer: true,
  },
  {
    moduleKey: "momentum_fail_fast",
    key: "momentum_fail_fast_signed_aggression_max",
    label: "Momentum Fail-fast Signed Aggression Max",
    type: "number",
    min: -1,
    max: 0,
    step: 0.01,
    fallback: -0.08,
    integer: false,
  },
  {
    moduleKey: "momentum_fail_fast",
    key: "momentum_fail_fast_book_pressure_max",
    label: "Momentum Fail-fast Book Pressure Max",
    type: "number",
    min: -1,
    max: 0,
    step: 0.01,
    fallback: -0.1,
    integer: false,
  },
  {
    moduleKey: "momentum_fail_fast",
    key: "momentum_fail_fast_directional_consistency_max",
    label: "Momentum Fail-fast Directional Consistency Max",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fallback: 0.2,
    integer: false,
  },
  {
    moduleKey: "momentum_diversification",
    key: "momentum_diversification_override_enabled",
    label: "Use Run-level Diversification Override",
    type: "boolean",
    fallback: false,
  },
  {
    moduleKey: "momentum_diversification",
    key: "momentum_require_l2_coverage",
    label: "Momentum Diversification Requires L2 Coverage",
    type: "boolean",
    fallback: true,
  },
];

export const EXECUTION_MODULE_PARAM_FIELDS_BY_MODULE = EXECUTION_MODULE_PARAM_FIELDS.reduce<Record<string, ExecutionModuleField[]>>(
  (acc, field) => {
    const moduleKey = String((field as { moduleKey?: unknown })?.moduleKey || "");
    if (!moduleKey) return acc;
    if (!Array.isArray(acc[moduleKey])) {
      acc[moduleKey] = [];
    }
    acc[moduleKey].push(field);
    return acc;
  },
  {},
);

export const ADAPTIVE_STUDIO_TABS = [
  { id: "profiles", label: "Unified Profiles", icon: "📋" },
  { id: "strategies", label: "Strategies", icon: "🎯" },
  { id: "modules", label: "Global Modules", icon: "🔧" },
  { id: "adaptive", label: "Adaptive", icon: "⚙" },
  { id: "flow", label: "Flow", icon: "🔀" },
] as const;
