from pathlib import Path

import duckdb

REPO_ROOT = Path(__file__).resolve().parents[1]

con = duckdb.connect(str(REPO_ROOT / "data" / "saas_state.db"))
print("Total GOOGL trades:", con.execute("SELECT count(*) FROM session_trades WHERE symbol='GOOGL'").fetchone()[0])

rejections = con.execute("""
    SELECT reason, count(*) 
    FROM decision_events 
    WHERE ticker='GOOGL' AND type='REJECT'
    GROUP BY reason
    ORDER BY count(*) DESC
""").fetchall()

print("\nRejections by reason:")
for r in rejections:
    print(f"  {r[0]}: {r[1]}")

signals = con.execute("""
    SELECT strategy, count(*) 
    FROM decision_events 
    WHERE ticker='GOOGL' AND type='SIGNAL_GENERATED'
    GROUP BY strategy
""").fetchall()

print("\nSignals generated by strategy:")
for s in signals:
    print(f"  {s[0]}: {s[1]}")
